apiVersion: v1
kind: Service
metadata:
  name: couchdb-peer0-org1
  labels: {
    component: peer0-org1,
    type: couchdb,
    org: org1
  }
spec:
  type: ClusterIP
  selector:
    component: peer0-org1
    type: couchdb
    org: org1
  ports:
    - port: 5984
      targetPort: 5984
