apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-peer0-org1
  labels: {
    component: peer0-org1,
    type: couchdb,
    org: org1
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer0-org1
      type: couchdb
      org: org1
  template:
    metadata:
      labels:
        component: peer0-org1
        type: couchdb
        org: org1
    spec:
      volumes:
        - name: host-mount
          persistentVolumeClaim:
            claimName: pv-storage-claim-test-network
      containers:
        - name: couchdb-peer0-org1
          image: couchdb:3.1.1
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: adminpw
            - name: NODENAME
              value: localhost
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: host-mount
              subPath: data/couchdb-peer0.org1.example.com
          resources:
            requests:
              cpu: 25m
              memory: 48Mi
            limits:
              cpu: 250m
              memory: 512Mi
