apiVersion: v1
kind: Service
metadata:
  name: couchdb-peer0-org2
  labels: {
    component: peer0-org2,
    type: couchdb,
    org: org2
  }
spec:
  type: ClusterIP
  selector:
    component: peer0-org2
    type: couchdb
    org: org2
  ports:
    - port: 5984
      targetPort: 5984
