apiVersion: v1
kind: Service
metadata:
  name: orderer1-orderer
  labels: {
    component: orderer,
    type: orderer-service
  }
spec:
  type: ClusterIP
  selector:
    component: orderer
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050
      name: port1
    - port: 7053
      targetPort: 7053
      name: port2
  
