apiVersion: v1
kind: Service
metadata:
  name: peer0-org1
  labels: {
    component: peer0-org1,
    type: peer,
    org: org1
  }
spec:
  type: ClusterIP
  selector:
    component: peer0-org1
    type: peer
    org: org1
  ports:
    - port: 7051
      targetPort: 7051
