kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-storage-claim-test-network
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: pv-storage-test-network